apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey-cluster.headlessServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey-cluster.labels" . | nindent 4 }}
  {{- with (merge .Values.service.headless.annotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: client
      port: {{ .Values.cluster.clientPort }}
      targetPort: client
      protocol: TCP
    - name: gossip
      port: {{ .Values.cluster.busPort }}
      targetPort: gossip
      protocol: TCP
  selector:
    {{- include "valkey-cluster.selectorLabels" . | nindent 4 }}
