// Package verbs holds verb executor implementations.
// Each verb is a primitive interface operation (nats_request, http_request, ...).
package verbs

import (
	"context"

	"github.com/nats-io/nats.go"
)

// Input carries the verb's resolved (post-placeholder-binding) input.
type Input struct {
	Site        string
	Subject     string
	Payload     []byte
	Credential  Credential // NATS user JWT + nkey seed for the actor
	Traceparent string     // generated by the dispatcher
}

// Credential identifies who is acting on the wire. Two sources are
// supported:
//
//   - User-level: JWT + NkeySeed minted at auth-service /auth at seed
//     time. Used for scenarios where a cast user makes a request
//     (`${requester.credential}` in the scenario YAML).
//   - Service-level: a CredsFile path pointing at a NATS .creds file
//     containing both the JWT and the nkey seed. Used for scenarios
//     that publish to service-internal subjects (e.g. the canonical
//     JetStream subjects room-worker consumes from — only services
//     have pub permission per the chatapp account's permission
//     boundary). Wired via `${service.backend}` and similar.
//
// Mutually exclusive — the verb's Connect path picks based on whether
// CredsFile is set.
type Credential struct {
	Account   string
	JWT       string
	NkeySeed  string
	CredsFile string
}

// Outcome is what a verb returns: either a reply payload, or a transport error.
type Outcome struct {
	Reply           []byte
	Header          nats.Header // headers from the reply message (nil on transport error)
	Err             error
	TraceparentEcho string // the dispatcher's set traceparent, repeated for the reader
	RequestID       string // UUIDv7 hyphenated, the X-Request-ID we set on the outbound request
}

// Executor is the interface every verb implementation satisfies.
type Executor interface {
	Execute(ctx context.Context, in *Input) Outcome
}
