// Code generated by MockGen. DO NOT EDIT.
// Source: dek_store.go
//
// Generated by this command:
//
//	mockgen -destination=mock_dek_store_test.go -package=atrest -source=dek_store.go DEKStore
//

// Package atrest is a generated GoMock package.
package atrest

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDEKStore is a mock of DEKStore interface.
type MockDEKStore struct {
	ctrl     *gomock.Controller
	recorder *MockDEKStoreMockRecorder
	isgomock struct{}
}

// MockDEKStoreMockRecorder is the mock recorder for MockDEKStore.
type MockDEKStoreMockRecorder struct {
	mock *MockDEKStore
}

// NewMockDEKStore creates a new mock instance.
func NewMockDEKStore(ctrl *gomock.Controller) *MockDEKStore {
	mock := &MockDEKStore{ctrl: ctrl}
	mock.recorder = &MockDEKStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDEKStore) EXPECT() *MockDEKStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDEKStore) Get(ctx context.Context, roomID string) (*RoomDataKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, roomID)
	ret0, _ := ret[0].(*RoomDataKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDEKStoreMockRecorder) Get(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDEKStore)(nil).Get), ctx, roomID)
}

// Replace mocks base method.
func (m *MockDEKStore) Replace(ctx context.Context, key RoomDataKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replace indicates an expected call of Replace.
func (mr *MockDEKStoreMockRecorder) Replace(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockDEKStore)(nil).Replace), ctx, key)
}

// Upsert mocks base method.
func (m *MockDEKStore) Upsert(ctx context.Context, key RoomDataKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockDEKStoreMockRecorder) Upsert(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockDEKStore)(nil).Upsert), ctx, key)
}
