// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/hmchangw/chat/pkg/model"
	msgraph "github.com/hmchangw/chat/pkg/msgraph"
	gomock "go.uber.org/mock/gomock"
)

// MockaccountLister is a mock of accountLister interface.
type MockaccountLister struct {
	ctrl     *gomock.Controller
	recorder *MockaccountListerMockRecorder
	isgomock struct{}
}

// MockaccountListerMockRecorder is the mock recorder for MockaccountLister.
type MockaccountListerMockRecorder struct {
	mock *MockaccountLister
}

// NewMockaccountLister creates a new mock instance.
func NewMockaccountLister(ctrl *gomock.Controller) *MockaccountLister {
	mock := &MockaccountLister{ctrl: ctrl}
	mock.recorder = &MockaccountListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccountLister) EXPECT() *MockaccountListerMockRecorder {
	return m.recorder
}

// ListSiteAccounts mocks base method.
func (m *MockaccountLister) ListSiteAccounts(ctx context.Context, siteID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSiteAccounts", ctx, siteID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSiteAccounts indicates an expected call of ListSiteAccounts.
func (mr *MockaccountListerMockRecorder) ListSiteAccounts(ctx, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSiteAccounts", reflect.TypeOf((*MockaccountLister)(nil).ListSiteAccounts), ctx, siteID)
}

// MockuserLister is a mock of userLister interface.
type MockuserLister struct {
	ctrl     *gomock.Controller
	recorder *MockuserListerMockRecorder
	isgomock struct{}
}

// MockuserListerMockRecorder is the mock recorder for MockuserLister.
type MockuserListerMockRecorder struct {
	mock *MockuserLister
}

// NewMockuserLister creates a new mock instance.
func NewMockuserLister(ctrl *gomock.Controller) *MockuserLister {
	mock := &MockuserLister{ctrl: ctrl}
	mock.recorder = &MockuserListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserLister) EXPECT() *MockuserListerMockRecorder {
	return m.recorder
}

// ListUsers mocks base method.
func (m *MockuserLister) ListUsers(ctx context.Context) ([]msgraph.GraphUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]msgraph.GraphUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockuserListerMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockuserLister)(nil).ListUsers), ctx)
}

// MockpresenceReader is a mock of presenceReader interface.
type MockpresenceReader struct {
	ctrl     *gomock.Controller
	recorder *MockpresenceReaderMockRecorder
	isgomock struct{}
}

// MockpresenceReaderMockRecorder is the mock recorder for MockpresenceReader.
type MockpresenceReaderMockRecorder struct {
	mock *MockpresenceReader
}

// NewMockpresenceReader creates a new mock instance.
func NewMockpresenceReader(ctrl *gomock.Controller) *MockpresenceReader {
	mock := &MockpresenceReader{ctrl: ctrl}
	mock.recorder = &MockpresenceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpresenceReader) EXPECT() *MockpresenceReaderMockRecorder {
	return m.recorder
}

// GetPresencesByUserId mocks base method.
func (m *MockpresenceReader) GetPresencesByUserId(ctx context.Context, ids []string) ([]msgraph.Presence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresencesByUserId", ctx, ids)
	ret0, _ := ret[0].([]msgraph.Presence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresencesByUserId indicates an expected call of GetPresencesByUserId.
func (mr *MockpresenceReaderMockRecorder) GetPresencesByUserId(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresencesByUserId", reflect.TypeOf((*MockpresenceReader)(nil).GetPresencesByUserId), ctx, ids)
}

// MockexternalApplier is a mock of externalApplier interface.
type MockexternalApplier struct {
	ctrl     *gomock.Controller
	recorder *MockexternalApplierMockRecorder
	isgomock struct{}
}

// MockexternalApplierMockRecorder is the mock recorder for MockexternalApplier.
type MockexternalApplierMockRecorder struct {
	mock *MockexternalApplier
}

// NewMockexternalApplier creates a new mock instance.
func NewMockexternalApplier(ctrl *gomock.Controller) *MockexternalApplier {
	mock := &MockexternalApplier{ctrl: ctrl}
	mock.recorder = &MockexternalApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexternalApplier) EXPECT() *MockexternalApplierMockRecorder {
	return m.recorder
}

// SetExternal mocks base method.
func (m *MockexternalApplier) SetExternal(ctx context.Context, account string, status model.PresenceStatus, ttl time.Duration) (bool, model.PresenceStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExternal", ctx, account, status, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(model.PresenceStatus)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetExternal indicates an expected call of SetExternal.
func (mr *MockexternalApplierMockRecorder) SetExternal(ctx, account, status, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExternal", reflect.TypeOf((*MockexternalApplier)(nil).SetExternal), ctx, account, status, ttl)
}

// MockinCallIndex is a mock of inCallIndex interface.
type MockinCallIndex struct {
	ctrl     *gomock.Controller
	recorder *MockinCallIndexMockRecorder
	isgomock struct{}
}

// MockinCallIndexMockRecorder is the mock recorder for MockinCallIndex.
type MockinCallIndexMockRecorder struct {
	mock *MockinCallIndex
}

// NewMockinCallIndex creates a new mock instance.
func NewMockinCallIndex(ctrl *gomock.Controller) *MockinCallIndex {
	mock := &MockinCallIndex{ctrl: ctrl}
	mock.recorder = &MockinCallIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinCallIndex) EXPECT() *MockinCallIndexMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockinCallIndex) Add(ctx context.Context, account string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockinCallIndexMockRecorder) Add(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockinCallIndex)(nil).Add), ctx, account)
}

// Members mocks base method.
func (m *MockinCallIndex) Members(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Members", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Members indicates an expected call of Members.
func (mr *MockinCallIndexMockRecorder) Members(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Members", reflect.TypeOf((*MockinCallIndex)(nil).Members), ctx)
}

// Remove mocks base method.
func (m *MockinCallIndex) Remove(ctx context.Context, account string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockinCallIndexMockRecorder) Remove(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockinCallIndex)(nil).Remove), ctx, account)
}

// MockidMapStore is a mock of idMapStore interface.
type MockidMapStore struct {
	ctrl     *gomock.Controller
	recorder *MockidMapStoreMockRecorder
	isgomock struct{}
}

// MockidMapStoreMockRecorder is the mock recorder for MockidMapStore.
type MockidMapStoreMockRecorder struct {
	mock *MockidMapStore
}

// NewMockidMapStore creates a new mock instance.
func NewMockidMapStore(ctrl *gomock.Controller) *MockidMapStore {
	mock := &MockidMapStore{ctrl: ctrl}
	mock.recorder = &MockidMapStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockidMapStore) EXPECT() *MockidMapStoreMockRecorder {
	return m.recorder
}

// Fresh mocks base method.
func (m *MockidMapStore) Fresh(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fresh", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fresh indicates an expected call of Fresh.
func (mr *MockidMapStoreMockRecorder) Fresh(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fresh", reflect.TypeOf((*MockidMapStore)(nil).Fresh), ctx)
}

// Refresh mocks base method.
func (m *MockidMapStore) Refresh(ctx context.Context, mapping map[string]string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, mapping, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockidMapStoreMockRecorder) Refresh(ctx, mapping, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockidMapStore)(nil).Refresh), ctx, mapping, ttl)
}

// Resolve mocks base method.
func (m *MockidMapStore) Resolve(ctx context.Context, accounts []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, accounts)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockidMapStoreMockRecorder) Resolve(ctx, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockidMapStore)(nil).Resolve), ctx, accounts)
}

// MockstatePublisher is a mock of statePublisher interface.
type MockstatePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockstatePublisherMockRecorder
	isgomock struct{}
}

// MockstatePublisherMockRecorder is the mock recorder for MockstatePublisher.
type MockstatePublisherMockRecorder struct {
	mock *MockstatePublisher
}

// NewMockstatePublisher creates a new mock instance.
func NewMockstatePublisher(ctrl *gomock.Controller) *MockstatePublisher {
	mock := &MockstatePublisher{ctrl: ctrl}
	mock.recorder = &MockstatePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatePublisher) EXPECT() *MockstatePublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockstatePublisher) Publish(ctx context.Context, account string, status model.PresenceStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", ctx, account, status)
}

// Publish indicates an expected call of Publish.
func (mr *MockstatePublisherMockRecorder) Publish(ctx, account, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockstatePublisher)(nil).Publish), ctx, account, status)
}
