// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mock_registry_test.go -package=main -typed
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockregistryAPI is a mock of registryAPI interface.
type MockregistryAPI struct {
	ctrl     *gomock.Controller
	recorder *MockregistryAPIMockRecorder
	isgomock struct{}
}

// MockregistryAPIMockRecorder is the mock recorder for MockregistryAPI.
type MockregistryAPIMockRecorder struct {
	mock *MockregistryAPI
}

// NewMockregistryAPI creates a new mock instance.
func NewMockregistryAPI(ctrl *gomock.Controller) *MockregistryAPI {
	mock := &MockregistryAPI{ctrl: ctrl}
	mock.recorder = &MockregistryAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockregistryAPI) EXPECT() *MockregistryAPIMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockregistryAPI) Close(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockregistryAPIMockRecorder) Close(id any) *MockregistryAPICloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockregistryAPI)(nil).Close), id)
	return &MockregistryAPICloseCall{Call: call}
}

// MockregistryAPICloseCall wrap *gomock.Call
type MockregistryAPICloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockregistryAPICloseCall) Return(arg0 error) *MockregistryAPICloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockregistryAPICloseCall) Do(f func(string) error) *MockregistryAPICloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockregistryAPICloseCall) DoAndReturn(f func(string) error) *MockregistryAPICloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CloseAll mocks base method.
func (m *MockregistryAPI) CloseAll() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseAll")
}

// CloseAll indicates an expected call of CloseAll.
func (mr *MockregistryAPIMockRecorder) CloseAll() *MockregistryAPICloseAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAll", reflect.TypeOf((*MockregistryAPI)(nil).CloseAll))
	return &MockregistryAPICloseAllCall{Call: call}
}

// MockregistryAPICloseAllCall wrap *gomock.Call
type MockregistryAPICloseAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockregistryAPICloseAllCall) Return() *MockregistryAPICloseAllCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockregistryAPICloseAllCall) Do(f func()) *MockregistryAPICloseAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockregistryAPICloseAllCall) DoAndReturn(f func()) *MockregistryAPICloseAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Connect mocks base method.
func (m *MockregistryAPI) Connect(ctx context.Context, spec connectSpec) (connInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, spec)
	ret0, _ := ret[0].(connInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockregistryAPIMockRecorder) Connect(ctx, spec any) *MockregistryAPIConnectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockregistryAPI)(nil).Connect), ctx, spec)
	return &MockregistryAPIConnectCall{Call: call}
}

// MockregistryAPIConnectCall wrap *gomock.Call
type MockregistryAPIConnectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockregistryAPIConnectCall) Return(arg0 connInfo, arg1 error) *MockregistryAPIConnectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockregistryAPIConnectCall) Do(f func(context.Context, connectSpec) (connInfo, error)) *MockregistryAPIConnectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockregistryAPIConnectCall) DoAndReturn(f func(context.Context, connectSpec) (connInfo, error)) *MockregistryAPIConnectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockregistryAPI) Get(id string) (*connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockregistryAPIMockRecorder) Get(id any) *MockregistryAPIGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockregistryAPI)(nil).Get), id)
	return &MockregistryAPIGetCall{Call: call}
}

// MockregistryAPIGetCall wrap *gomock.Call
type MockregistryAPIGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockregistryAPIGetCall) Return(arg0 *connection, arg1 error) *MockregistryAPIGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockregistryAPIGetCall) Do(f func(string) (*connection, error)) *MockregistryAPIGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockregistryAPIGetCall) DoAndReturn(f func(string) (*connection, error)) *MockregistryAPIGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockregistryAPI) List() []connInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]connInfo)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockregistryAPIMockRecorder) List() *MockregistryAPIListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockregistryAPI)(nil).List))
	return &MockregistryAPIListCall{Call: call}
}

// MockregistryAPIListCall wrap *gomock.Call
type MockregistryAPIListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockregistryAPIListCall) Return(arg0 []connInfo) *MockregistryAPIListCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockregistryAPIListCall) Do(f func() []connInfo) *MockregistryAPIListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockregistryAPIListCall) DoAndReturn(f func() []connInfo) *MockregistryAPIListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
