// Code generated by MockGen. DO NOT EDIT.
// Source: mongo_ops.go
//
// Generated by this command:
//
//	mockgen -source=mongo_ops.go -destination=mock_mongo_ops_test.go -package=main -typed
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	bson "go.mongodb.org/mongo-driver/v2/bson"
	mongo "go.mongodb.org/mongo-driver/v2/mongo"
	gomock "go.uber.org/mock/gomock"
)

// MockmongoOps is a mock of mongoOps interface.
type MockmongoOps struct {
	ctrl     *gomock.Controller
	recorder *MockmongoOpsMockRecorder
	isgomock struct{}
}

// MockmongoOpsMockRecorder is the mock recorder for MockmongoOps.
type MockmongoOpsMockRecorder struct {
	mock *MockmongoOps
}

// NewMockmongoOps creates a new mock instance.
func NewMockmongoOps(ctrl *gomock.Controller) *MockmongoOps {
	mock := &MockmongoOps{ctrl: ctrl}
	mock.recorder = &MockmongoOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmongoOps) EXPECT() *MockmongoOpsMockRecorder {
	return m.recorder
}

// DeleteDoc mocks base method.
func (m *MockmongoOps) DeleteDoc(ctx context.Context, client *mongo.Client, db, coll string, id any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDoc", ctx, client, db, coll, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDoc indicates an expected call of DeleteDoc.
func (mr *MockmongoOpsMockRecorder) DeleteDoc(ctx, client, db, coll, id any) *MockmongoOpsDeleteDocCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDoc", reflect.TypeOf((*MockmongoOps)(nil).DeleteDoc), ctx, client, db, coll, id)
	return &MockmongoOpsDeleteDocCall{Call: call}
}

// MockmongoOpsDeleteDocCall wrap *gomock.Call
type MockmongoOpsDeleteDocCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockmongoOpsDeleteDocCall) Return(arg0 error) *MockmongoOpsDeleteDocCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockmongoOpsDeleteDocCall) Do(f func(context.Context, *mongo.Client, string, string, any) error) *MockmongoOpsDeleteDocCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockmongoOpsDeleteDocCall) DoAndReturn(f func(context.Context, *mongo.Client, string, string, any) error) *MockmongoOpsDeleteDocCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InsertDoc mocks base method.
func (m *MockmongoOps) InsertDoc(ctx context.Context, client *mongo.Client, db, coll string, doc bson.M) (bson.M, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDoc", ctx, client, db, coll, doc)
	ret0, _ := ret[0].(bson.M)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertDoc indicates an expected call of InsertDoc.
func (mr *MockmongoOpsMockRecorder) InsertDoc(ctx, client, db, coll, doc any) *MockmongoOpsInsertDocCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDoc", reflect.TypeOf((*MockmongoOps)(nil).InsertDoc), ctx, client, db, coll, doc)
	return &MockmongoOpsInsertDocCall{Call: call}
}

// MockmongoOpsInsertDocCall wrap *gomock.Call
type MockmongoOpsInsertDocCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockmongoOpsInsertDocCall) Return(arg0 bson.M, arg1 error) *MockmongoOpsInsertDocCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockmongoOpsInsertDocCall) Do(f func(context.Context, *mongo.Client, string, string, bson.M) (bson.M, error)) *MockmongoOpsInsertDocCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockmongoOpsInsertDocCall) DoAndReturn(f func(context.Context, *mongo.Client, string, string, bson.M) (bson.M, error)) *MockmongoOpsInsertDocCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListCollections mocks base method.
func (m *MockmongoOps) ListCollections(ctx context.Context, client *mongo.Client, db string) ([]collectionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollections", ctx, client, db)
	ret0, _ := ret[0].([]collectionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCollections indicates an expected call of ListCollections.
func (mr *MockmongoOpsMockRecorder) ListCollections(ctx, client, db any) *MockmongoOpsListCollectionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollections", reflect.TypeOf((*MockmongoOps)(nil).ListCollections), ctx, client, db)
	return &MockmongoOpsListCollectionsCall{Call: call}
}

// MockmongoOpsListCollectionsCall wrap *gomock.Call
type MockmongoOpsListCollectionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockmongoOpsListCollectionsCall) Return(arg0 []collectionInfo, arg1 error) *MockmongoOpsListCollectionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockmongoOpsListCollectionsCall) Do(f func(context.Context, *mongo.Client, string) ([]collectionInfo, error)) *MockmongoOpsListCollectionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockmongoOpsListCollectionsCall) DoAndReturn(f func(context.Context, *mongo.Client, string) ([]collectionInfo, error)) *MockmongoOpsListCollectionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListDocs mocks base method.
func (m *MockmongoOps) ListDocs(ctx context.Context, client *mongo.Client, db, coll string, filter bson.M, skip, limit int64) (listDocsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDocs", ctx, client, db, coll, filter, skip, limit)
	ret0, _ := ret[0].(listDocsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDocs indicates an expected call of ListDocs.
func (mr *MockmongoOpsMockRecorder) ListDocs(ctx, client, db, coll, filter, skip, limit any) *MockmongoOpsListDocsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDocs", reflect.TypeOf((*MockmongoOps)(nil).ListDocs), ctx, client, db, coll, filter, skip, limit)
	return &MockmongoOpsListDocsCall{Call: call}
}

// MockmongoOpsListDocsCall wrap *gomock.Call
type MockmongoOpsListDocsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockmongoOpsListDocsCall) Return(arg0 listDocsResult, arg1 error) *MockmongoOpsListDocsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockmongoOpsListDocsCall) Do(f func(context.Context, *mongo.Client, string, string, bson.M, int64, int64) (listDocsResult, error)) *MockmongoOpsListDocsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockmongoOpsListDocsCall) DoAndReturn(f func(context.Context, *mongo.Client, string, string, bson.M, int64, int64) (listDocsResult, error)) *MockmongoOpsListDocsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReplaceDoc mocks base method.
func (m *MockmongoOps) ReplaceDoc(ctx context.Context, client *mongo.Client, db, coll string, id any, doc bson.M) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceDoc", ctx, client, db, coll, id, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceDoc indicates an expected call of ReplaceDoc.
func (mr *MockmongoOpsMockRecorder) ReplaceDoc(ctx, client, db, coll, id, doc any) *MockmongoOpsReplaceDocCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceDoc", reflect.TypeOf((*MockmongoOps)(nil).ReplaceDoc), ctx, client, db, coll, id, doc)
	return &MockmongoOpsReplaceDocCall{Call: call}
}

// MockmongoOpsReplaceDocCall wrap *gomock.Call
type MockmongoOpsReplaceDocCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockmongoOpsReplaceDocCall) Return(arg0 error) *MockmongoOpsReplaceDocCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockmongoOpsReplaceDocCall) Do(f func(context.Context, *mongo.Client, string, string, any, bson.M) error) *MockmongoOpsReplaceDocCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockmongoOpsReplaceDocCall) DoAndReturn(f func(context.Context, *mongo.Client, string, string, any, bson.M) error) *MockmongoOpsReplaceDocCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
