// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/user-service/service (interfaces: SubscriptionRepository,UserRepository,AppRepository,RoomClient,EventPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repository.go -package=mocks . SubscriptionRepository,UserRepository,AppRepository,RoomClient,EventPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	mongoutil "github.com/hmchangw/chat/pkg/mongoutil"
	models "github.com/hmchangw/chat/user-service/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// AggregateSubscriptions mocks base method.
func (m *MockSubscriptionRepository) AggregateSubscriptions(ctx context.Context, account, listType string, withinDays *int, limit int) ([]model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateSubscriptions", ctx, account, listType, withinDays, limit)
	ret0, _ := ret[0].([]model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AggregateSubscriptions indicates an expected call of AggregateSubscriptions.
func (mr *MockSubscriptionRepositoryMockRecorder) AggregateSubscriptions(ctx, account, listType, withinDays, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateSubscriptions", reflect.TypeOf((*MockSubscriptionRepository)(nil).AggregateSubscriptions), ctx, account, listType, withinDays, limit)
}

// CountActiveSubscriptions mocks base method.
func (m *MockSubscriptionRepository) CountActiveSubscriptions(ctx context.Context, account string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveSubscriptions", ctx, account)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveSubscriptions indicates an expected call of CountActiveSubscriptions.
func (mr *MockSubscriptionRepositoryMockRecorder) CountActiveSubscriptions(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveSubscriptions", reflect.TypeOf((*MockSubscriptionRepository)(nil).CountActiveSubscriptions), ctx, account)
}

// FindChannelsByMembers mocks base method.
func (m *MockSubscriptionRepository) FindChannelsByMembers(ctx context.Context, account string, members []string, limit int) ([]model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindChannelsByMembers", ctx, account, members, limit)
	ret0, _ := ret[0].([]model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindChannelsByMembers indicates an expected call of FindChannelsByMembers.
func (mr *MockSubscriptionRepositoryMockRecorder) FindChannelsByMembers(ctx, account, members, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindChannelsByMembers", reflect.TypeOf((*MockSubscriptionRepository)(nil).FindChannelsByMembers), ctx, account, members, limit)
}

// GetActiveSubscriptions mocks base method.
func (m *MockSubscriptionRepository) GetActiveSubscriptions(ctx context.Context, account string, limit int) ([]model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSubscriptions", ctx, account, limit)
	ret0, _ := ret[0].([]model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSubscriptions indicates an expected call of GetActiveSubscriptions.
func (mr *MockSubscriptionRepositoryMockRecorder) GetActiveSubscriptions(ctx, account, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSubscriptions", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetActiveSubscriptions), ctx, account, limit)
}

// GetAppSubscription mocks base method.
func (m *MockSubscriptionRepository) GetAppSubscription(ctx context.Context, account, botName string) (*model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppSubscription", ctx, account, botName)
	ret0, _ := ret[0].(*model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppSubscription indicates an expected call of GetAppSubscription.
func (mr *MockSubscriptionRepositoryMockRecorder) GetAppSubscription(ctx, account, botName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppSubscription", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetAppSubscription), ctx, account, botName)
}

// GetDMSubscription mocks base method.
func (m *MockSubscriptionRepository) GetDMSubscription(ctx context.Context, account, target string) (*model.DMSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDMSubscription", ctx, account, target)
	ret0, _ := ret[0].(*model.DMSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDMSubscription indicates an expected call of GetDMSubscription.
func (mr *MockSubscriptionRepositoryMockRecorder) GetDMSubscription(ctx, account, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDMSubscription", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetDMSubscription), ctx, account, target)
}

// GetSubscriptionByRoomID mocks base method.
func (m *MockSubscriptionRepository) GetSubscriptionByRoomID(ctx context.Context, account, roomID string) (*model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionByRoomID", ctx, account, roomID)
	ret0, _ := ret[0].(*model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionByRoomID indicates an expected call of GetSubscriptionByRoomID.
func (mr *MockSubscriptionRepositoryMockRecorder) GetSubscriptionByRoomID(ctx, account, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionByRoomID", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetSubscriptionByRoomID), ctx, account, roomID)
}

// SetAppSubscribed mocks base method.
func (m *MockSubscriptionRepository) SetAppSubscribed(ctx context.Context, account, botName string, subscribed, muted bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAppSubscribed", ctx, account, botName, subscribed, muted)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAppSubscribed indicates an expected call of SetAppSubscribed.
func (mr *MockSubscriptionRepositoryMockRecorder) SetAppSubscribed(ctx, account, botName, subscribed, muted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAppSubscribed", reflect.TypeOf((*MockSubscriptionRepository)(nil).SetAppSubscribed), ctx, account, botName, subscribed, muted)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetUserStatus mocks base method.
func (m *MockUserRepository) GetUserStatus(ctx context.Context, account string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStatus", ctx, account)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStatus indicates an expected call of GetUserStatus.
func (mr *MockUserRepositoryMockRecorder) GetUserStatus(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStatus", reflect.TypeOf((*MockUserRepository)(nil).GetUserStatus), ctx, account)
}

// SetUserStatus mocks base method.
func (m *MockUserRepository) SetUserStatus(ctx context.Context, account, text string, isShow *bool) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserStatus", ctx, account, text, isShow)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserStatus indicates an expected call of SetUserStatus.
func (mr *MockUserRepositoryMockRecorder) SetUserStatus(ctx, account, text, isShow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserStatus", reflect.TypeOf((*MockUserRepository)(nil).SetUserStatus), ctx, account, text, isShow)
}

// MockAppRepository is a mock of AppRepository interface.
type MockAppRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAppRepositoryMockRecorder
	isgomock struct{}
}

// MockAppRepositoryMockRecorder is the mock recorder for MockAppRepository.
type MockAppRepositoryMockRecorder struct {
	mock *MockAppRepository
}

// NewMockAppRepository creates a new mock instance.
func NewMockAppRepository(ctrl *gomock.Controller) *MockAppRepository {
	mock := &MockAppRepository{ctrl: ctrl}
	mock.recorder = &MockAppRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppRepository) EXPECT() *MockAppRepositoryMockRecorder {
	return m.recorder
}

// GetApp mocks base method.
func (m *MockAppRepository) GetApp(ctx context.Context, appID string) (*model.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApp", ctx, appID)
	ret0, _ := ret[0].(*model.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApp indicates an expected call of GetApp.
func (mr *MockAppRepositoryMockRecorder) GetApp(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApp", reflect.TypeOf((*MockAppRepository)(nil).GetApp), ctx, appID)
}

// GetAppNamesByAssistants mocks base method.
func (m *MockAppRepository) GetAppNamesByAssistants(ctx context.Context, botAccounts []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppNamesByAssistants", ctx, botAccounts)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppNamesByAssistants indicates an expected call of GetAppNamesByAssistants.
func (mr *MockAppRepositoryMockRecorder) GetAppNamesByAssistants(ctx, botAccounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppNamesByAssistants", reflect.TypeOf((*MockAppRepository)(nil).GetAppNamesByAssistants), ctx, botAccounts)
}

// ListApps mocks base method.
func (m *MockAppRepository) ListApps(ctx context.Context, account string, page mongoutil.OffsetPageRequest) (mongoutil.OffsetPage[models.AppListItem], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApps", ctx, account, page)
	ret0, _ := ret[0].(mongoutil.OffsetPage[models.AppListItem])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApps indicates an expected call of ListApps.
func (mr *MockAppRepositoryMockRecorder) ListApps(ctx, account, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApps", reflect.TypeOf((*MockAppRepository)(nil).ListApps), ctx, account, page)
}

// MockRoomClient is a mock of RoomClient interface.
type MockRoomClient struct {
	ctrl     *gomock.Controller
	recorder *MockRoomClientMockRecorder
	isgomock struct{}
}

// MockRoomClientMockRecorder is the mock recorder for MockRoomClient.
type MockRoomClientMockRecorder struct {
	mock *MockRoomClient
}

// NewMockRoomClient creates a new mock instance.
func NewMockRoomClient(ctrl *gomock.Controller) *MockRoomClient {
	mock := &MockRoomClient{ctrl: ctrl}
	mock.recorder = &MockRoomClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomClient) EXPECT() *MockRoomClientMockRecorder {
	return m.recorder
}

// CreateDMRoom mocks base method.
func (m *MockRoomClient) CreateDMRoom(ctx context.Context, account, otherAccount string, roomType model.RoomType) (model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDMRoom", ctx, account, otherAccount, roomType)
	ret0, _ := ret[0].(model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDMRoom indicates an expected call of CreateDMRoom.
func (mr *MockRoomClientMockRecorder) CreateDMRoom(ctx, account, otherAccount, roomType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDMRoom", reflect.TypeOf((*MockRoomClient)(nil).CreateDMRoom), ctx, account, otherAccount, roomType)
}

// GetRoomsInfo mocks base method.
func (m *MockRoomClient) GetRoomsInfo(ctx context.Context, siteID string, roomIDs []string) ([]model.RoomInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomsInfo", ctx, siteID, roomIDs)
	ret0, _ := ret[0].([]model.RoomInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomsInfo indicates an expected call of GetRoomsInfo.
func (mr *MockRoomClientMockRecorder) GetRoomsInfo(ctx, siteID, roomIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomsInfo", reflect.TypeOf((*MockRoomClient)(nil).GetRoomsInfo), ctx, siteID, roomIDs)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockEventPublisher) Publish(ctx context.Context, subject string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, subject, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventPublisherMockRecorder) Publish(ctx, subject, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventPublisher)(nil).Publish), ctx, subject, data)
}
