#!/usr/bin/env bash
#
# Generates NATS operator + account keys and writes .env + nats.conf.
# Uses the nats-box Docker image so it works on any OS (Mac, Ubuntu, etc.)
# without requiring local nsc/nk installation.
#
# Run once before `docker compose up`.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
NATS_CONF="$SCRIPT_DIR/nats.conf"
NATS_BOX_IMAGE="natsio/nats-box:latest"

echo "=== Auth Service — Local Dev Setup ==="
echo ""

# Check Docker
if ! command -v docker &>/dev/null; then
  echo "ERROR: docker not found. Install Docker first."
  exit 1
fi

echo "Generating NATS operator + account keys via nats-box..."
echo ""

# Run nsc inside nats-box to generate operator, SYS account, and chatapp account.
# Mount a temp dir to extract the generated data.
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

docker run --rm \
  -v "$TMPDIR:/output" \
  "$NATS_BOX_IMAGE" \
  sh -c '
    set -e

    # Create operator with SYS account
    nsc add operator --name localdev --sys 2>&1 | sed "s/^/  /"
    nsc env -o localdev >/dev/null 2>&1

    # Create chatapp account
    nsc add account --name chatapp 2>&1 | sed "s/^/  /"
    nsc edit account chatapp --js-mem-storage 512M --js-disk-storage 5G --js-streams 10 2>&1 | sed "s/^/  /"

    # Extract JWTs
    nsc describe operator --raw > /output/operator.jwt
    nsc describe account chatapp --raw > /output/account.jwt
    nsc describe account SYS --raw > /output/sys.jwt

    # Extract public keys
    nsc describe account chatapp 2>/dev/null | grep "Account ID" | awk -F"|" "{gsub(/[ \t]/, \"\", \$3); print \$3}" > /output/account_pub.txt
    nsc describe account SYS 2>/dev/null | grep "Account ID" | awk -F"|" "{gsub(/[ \t]/, \"\", \$3); print \$3}" > /output/sys_pub.txt

    # Find and copy account seed
    ACCOUNT_PUB=$(cat /output/account_pub.txt)
    SEED_FILE=$(find /root/.local/share/nats/nsc/keys -name "${ACCOUNT_PUB}.nk" 2>/dev/null | head -1)
    if [ -z "$SEED_FILE" ]; then
      # Fallback: search nsc default store
      SEED_FILE=$(find /nsc -name "${ACCOUNT_PUB}.nk" 2>/dev/null | head -1)
    fi

    if [ -z "$SEED_FILE" ]; then
      echo "ERROR: Could not find account seed for ${ACCOUNT_PUB}"
      exit 1
    fi

    cat "$SEED_FILE" > /output/account_seed.txt

    # Create the backend user JWT
    nsc add user --account chatapp --name backend
    nsc edit user --account chatapp --name backend --allow-sub ">" --allow-pub ">"
    nsc generate creds --account chatapp --name backend > /output/backend.creds

  '

# Get backend user JWT
cp "$TMPDIR/backend.creds" backend.creds

# Read generated values
OPERATOR_JWT=$(cat "$TMPDIR/operator.jwt")
ACCOUNT_JWT=$(cat "$TMPDIR/account.jwt")
SYS_JWT=$(cat "$TMPDIR/sys.jwt")
ACCOUNT_PUB_KEY=$(cat "$TMPDIR/account_pub.txt")
SYS_PUB_KEY=$(cat "$TMPDIR/sys_pub.txt")
ACCOUNT_SEED=$(cat "$TMPDIR/account_seed.txt")

echo ""
echo "  Operator JWT:       ${OPERATOR_JWT:0:50}..."
echo "  Account Public Key: $ACCOUNT_PUB_KEY"
echo "  Account JWT:        ${ACCOUNT_JWT:0:50}..."
echo "  Account Seed:       ${ACCOUNT_SEED:0:12}..."
echo "  SYS Public Key:     $SYS_PUB_KEY"
echo "  User JWT:           backend.creds"
echo ""

# Write .env
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh — do not commit this file
# Regenerate with: ./setup.sh

# === NATS ===
AUTH_SIGNING_KEY=${ACCOUNT_SEED}

# === Auth Service ===
PORT=8080
NATS_JWT_EXPIRY=2h

# === OIDC / Keycloak (local dev) ===
# Uses Docker service name since auth-service runs inside Docker network.
OIDC_ISSUER_URL=http://keycloak:8080/realms/chatapp
OIDC_AUDIENCE=nats-chat
OIDC_VERIFY_AZP=true
TLS_SKIP_VERIFY=false

# === NATS config generation values (used by nats.conf) ===
NATS_ACCOUNT_PUBLIC_KEY=${ACCOUNT_PUB_KEY}
NATS_ACCOUNT_JWT=${ACCOUNT_JWT}
NATS_OPERATOR_JWT=${OPERATOR_JWT}
NATS_SYS_PUBLIC_KEY=${SYS_PUB_KEY}
NATS_SYS_JWT=${SYS_JWT}
EOF

# Write nats.conf with baked-in values (NATS doesn't support env vars in map keys)
cat > "$NATS_CONF" <<EOF
# Generated by setup.sh — do not commit this file
# Regenerate with: ./setup.sh

port: 4222
http_port: 8222

operator: ${OPERATOR_JWT}

resolver: MEMORY

resolver_preload {
  ${ACCOUNT_PUB_KEY}: ${ACCOUNT_JWT}
  ${SYS_PUB_KEY}: ${SYS_JWT}
}

jetstream {
  store_dir: /data/jetstream
  max_mem: 1G
  max_file: 10G
}

websocket {
  port: 9222
  no_tls: true
}
EOF

echo "Wrote $ENV_FILE"
echo "Wrote $NATS_CONF"
echo ""
echo "=== Ready! ==="
echo ""
echo "  # Start all services (Keycloak + NATS + Auth Service)"
echo "  cd $SCRIPT_DIR"
echo "  docker compose up -d"
echo ""
echo "  # Wait for Keycloak to be ready (~30-60s)"
echo "  docker compose logs -f keycloak  # watch for 'Listening on'"
echo ""
echo "  ──────────────────────────────────────"
echo "  Keycloak Admin:   http://localhost:9090  (admin / admin)"
echo "  Auth Service:     http://localhost:8080"
echo "  NATS Monitoring:  http://localhost:8222"
echo "  NATS WebSocket:   ws://localhost:9222"
echo "  ──────────────────────────────────────"
echo ""
echo "  Test users: testuser/testuser  alice/alice"
echo ""
