// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/roomkeystore/roomkeystore.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/roomkeystore/roomkeystore.go -destination=mock_keystore_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	roomkeystore "github.com/hmchangw/chat/pkg/roomkeystore"
	gomock "go.uber.org/mock/gomock"
)

// MockRoomKeyStore is a mock of RoomKeyStore interface.
type MockRoomKeyStore struct {
	ctrl     *gomock.Controller
	recorder *MockRoomKeyStoreMockRecorder
	isgomock struct{}
}

// MockRoomKeyStoreMockRecorder is the mock recorder for MockRoomKeyStore.
type MockRoomKeyStoreMockRecorder struct {
	mock *MockRoomKeyStore
}

// NewMockRoomKeyStore creates a new mock instance.
func NewMockRoomKeyStore(ctrl *gomock.Controller) *MockRoomKeyStore {
	mock := &MockRoomKeyStore{ctrl: ctrl}
	mock.recorder = &MockRoomKeyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomKeyStore) EXPECT() *MockRoomKeyStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRoomKeyStore) Delete(ctx context.Context, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoomKeyStoreMockRecorder) Delete(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoomKeyStore)(nil).Delete), ctx, roomID)
}

// Get mocks base method.
func (m *MockRoomKeyStore) Get(ctx context.Context, roomID string) (*roomkeystore.VersionedKeyPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, roomID)
	ret0, _ := ret[0].(*roomkeystore.VersionedKeyPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRoomKeyStoreMockRecorder) Get(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRoomKeyStore)(nil).Get), ctx, roomID)
}

// GetByVersion mocks base method.
func (m *MockRoomKeyStore) GetByVersion(ctx context.Context, roomID string, version int) (*roomkeystore.RoomKeyPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByVersion", ctx, roomID, version)
	ret0, _ := ret[0].(*roomkeystore.RoomKeyPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByVersion indicates an expected call of GetByVersion.
func (mr *MockRoomKeyStoreMockRecorder) GetByVersion(ctx, roomID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByVersion", reflect.TypeOf((*MockRoomKeyStore)(nil).GetByVersion), ctx, roomID, version)
}

// GetMany mocks base method.
func (m *MockRoomKeyStore) GetMany(ctx context.Context, roomIDs []string) (map[string]*roomkeystore.VersionedKeyPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMany", ctx, roomIDs)
	ret0, _ := ret[0].(map[string]*roomkeystore.VersionedKeyPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMany indicates an expected call of GetMany.
func (mr *MockRoomKeyStoreMockRecorder) GetMany(ctx, roomIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMany", reflect.TypeOf((*MockRoomKeyStore)(nil).GetMany), ctx, roomIDs)
}

// Rotate mocks base method.
func (m *MockRoomKeyStore) Rotate(ctx context.Context, roomID string, newPair roomkeystore.RoomKeyPair) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx, roomID, newPair)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rotate indicates an expected call of Rotate.
func (mr *MockRoomKeyStoreMockRecorder) Rotate(ctx, roomID, newPair any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockRoomKeyStore)(nil).Rotate), ctx, roomID, newPair)
}

// Set mocks base method.
func (m *MockRoomKeyStore) Set(ctx context.Context, roomID string, pair roomkeystore.RoomKeyPair) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, roomID, pair)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockRoomKeyStoreMockRecorder) Set(ctx, roomID, pair any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRoomKeyStore)(nil).Set), ctx, roomID, pair)
}

// MockhashCommander is a mock of hashCommander interface.
type MockhashCommander struct {
	ctrl     *gomock.Controller
	recorder *MockhashCommanderMockRecorder
	isgomock struct{}
}

// MockhashCommanderMockRecorder is the mock recorder for MockhashCommander.
type MockhashCommanderMockRecorder struct {
	mock *MockhashCommander
}

// NewMockhashCommander creates a new mock instance.
func NewMockhashCommander(ctrl *gomock.Controller) *MockhashCommander {
	mock := &MockhashCommander{ctrl: ctrl}
	mock.recorder = &MockhashCommanderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhashCommander) EXPECT() *MockhashCommanderMockRecorder {
	return m.recorder
}

// deletePipeline mocks base method.
func (m *MockhashCommander) deletePipeline(ctx context.Context, currentKey, prevKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "deletePipeline", ctx, currentKey, prevKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// deletePipeline indicates an expected call of deletePipeline.
func (mr *MockhashCommanderMockRecorder) deletePipeline(ctx, currentKey, prevKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "deletePipeline", reflect.TypeOf((*MockhashCommander)(nil).deletePipeline), ctx, currentKey, prevKey)
}

// hgetall mocks base method.
func (m *MockhashCommander) hgetall(ctx context.Context, key string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "hgetall", ctx, key)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// hgetall indicates an expected call of hgetall.
func (mr *MockhashCommanderMockRecorder) hgetall(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "hgetall", reflect.TypeOf((*MockhashCommander)(nil).hgetall), ctx, key)
}

// hgetallMany mocks base method.
func (m *MockhashCommander) hgetallMany(ctx context.Context, keys []string) ([]map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "hgetallMany", ctx, keys)
	ret0, _ := ret[0].([]map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// hgetallMany indicates an expected call of hgetallMany.
func (mr *MockhashCommanderMockRecorder) hgetallMany(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "hgetallMany", reflect.TypeOf((*MockhashCommander)(nil).hgetallMany), ctx, keys)
}

// hset mocks base method.
func (m *MockhashCommander) hset(ctx context.Context, key, pub, priv string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "hset", ctx, key, pub, priv)
	ret0, _ := ret[0].(error)
	return ret0
}

// hset indicates an expected call of hset.
func (mr *MockhashCommanderMockRecorder) hset(ctx, key, pub, priv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "hset", reflect.TypeOf((*MockhashCommander)(nil).hset), ctx, key, pub, priv)
}

// rotatePipeline mocks base method.
func (m *MockhashCommander) rotatePipeline(ctx context.Context, currentKey, prevKey, pub, priv string, gracePeriod time.Duration) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "rotatePipeline", ctx, currentKey, prevKey, pub, priv, gracePeriod)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// rotatePipeline indicates an expected call of rotatePipeline.
func (mr *MockhashCommanderMockRecorder) rotatePipeline(ctx, currentKey, prevKey, pub, priv, gracePeriod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "rotatePipeline", reflect.TypeOf((*MockhashCommander)(nil).rotatePipeline), ctx, currentKey, prevKey, pub, priv, gracePeriod)
}
