package infra

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// natsTrustChainFiles lists the docker-local artifacts every microservice
// relies on to authenticate with NATS:
//   - .env carries AUTH_SIGNING_KEY (the chatapp account nkey seed)
//   - backend.creds carries the JWT+seed every non-auth service uses to
//     connect
//   - nats.conf wires the operator JWT + resolver_preload so the NATS
//     server actually validates the JWTs the rest of the stack presents
//
// Generated by docker-local/setup.sh. If any of these is missing,
// auth-service panics on startup and every other service fails its
// NATS handshake — manifesting as a confusing 90-second Cassandra-boot
// timeline followed by service-side fatal logs.
//
// Note: the filename is `nats.conf` (not `nats-server.conf`). setup.sh
// writes that exact name; compose.deps.yaml + the Makefile reference
// it; we mirror.
var natsTrustChainFiles = []string{".env", "backend.creds", "nats.conf"}

// verifyNATSTrustChain returns a descriptive error when any of the
// docker-local trust-chain files is missing. Called from infra.Up
// before any container starts so the operator gets the actionable
// error instead of a 90-second wait followed by a cryptic NATS auth
// rejection.
func verifyNATSTrustChain(repoRoot string) error {
	var missing []string
	for _, name := range natsTrustChainFiles {
		path := filepath.Join(repoRoot, "docker-local", name)
		if _, err := os.Stat(path); err != nil {
			missing = append(missing, path)
		}
	}
	if len(missing) == 0 {
		return nil
	}
	// Lowercase per Go convention (staticcheck ST1005). Operator-facing
	// remediation comes second so it survives any wrapping context.
	return fmt.Errorf("missing NATS trust chain files — run ./docker-local/setup.sh to generate local credentials.\n  missing:\n    - %s",
		strings.Join(missing, "\n    - "))
}

// loadEnvFile reads a KEY=value shell-style .env file and returns its
// contents as a map. Blank lines and `#`-prefixed comments are ignored;
// inline comments are not stripped (the local .env file doesn't use
// any, and the setup.sh format only emits two value styles, neither of
// which contains `#`). Values may NOT be quoted today — setup.sh
// writes raw nkey seeds and URLs without quoting.
func loadEnvFile(path string) (map[string]string, error) {
	f, err := os.Open(path) //nolint:gosec // path comes from resolveRepoRoot, not user input
	if err != nil {
		return nil, fmt.Errorf("loadEnvFile %s: %w", path, err)
	}
	defer f.Close() //nolint:errcheck

	out := map[string]string{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.IndexByte(line, '=')
		if idx <= 0 {
			continue
		}
		key := strings.TrimSpace(line[:idx])
		val := strings.TrimSpace(line[idx+1:])
		out[key] = val
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("loadEnvFile %s: scan: %w", path, err)
	}
	return out, nil
}

// loadAuthSigningKey parses AUTH_SIGNING_KEY out of docker-local/.env.
// Returns an error if the file isn't readable or the key isn't set —
// both are operator-facing problems (re-run setup.sh).
func loadAuthSigningKey(repoRoot string) (string, error) {
	envPath := filepath.Join(repoRoot, "docker-local", ".env")
	env, err := loadEnvFile(envPath)
	if err != nil {
		return "", err
	}
	key, ok := env["AUTH_SIGNING_KEY"]
	if !ok || key == "" {
		return "", fmt.Errorf("AUTH_SIGNING_KEY missing or empty in %s — re-run ./docker-local/setup.sh", envPath)
	}
	return key, nil
}
