// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDirectoryStore is a mock of DirectoryStore interface.
type MockDirectoryStore struct {
	ctrl     *gomock.Controller
	recorder *MockDirectoryStoreMockRecorder
	isgomock struct{}
}

// MockDirectoryStoreMockRecorder is the mock recorder for MockDirectoryStore.
type MockDirectoryStoreMockRecorder struct {
	mock *MockDirectoryStore
}

// NewMockDirectoryStore creates a new mock instance.
func NewMockDirectoryStore(ctrl *gomock.Controller) *MockDirectoryStore {
	mock := &MockDirectoryStore{ctrl: ctrl}
	mock.recorder = &MockDirectoryStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirectoryStore) EXPECT() *MockDirectoryStoreMockRecorder {
	return m.recorder
}

// ListEmployees mocks base method.
func (m *MockDirectoryStore) ListEmployees(ctx context.Context) ([]employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployees", ctx)
	ret0, _ := ret[0].([]employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployees indicates an expected call of ListEmployees.
func (mr *MockDirectoryStoreMockRecorder) ListEmployees(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployees", reflect.TypeOf((*MockDirectoryStore)(nil).ListEmployees), ctx)
}
