// Code generated by MockGen. DO NOT EDIT.
// Source: oidclogin.go
//
// Generated by this command:
//
//	mockgen -source=oidclogin.go -destination=mock_oidclogin_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockloginAuthenticator is a mock of loginAuthenticator interface.
type MockloginAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockloginAuthenticatorMockRecorder
	isgomock struct{}
}

// MockloginAuthenticatorMockRecorder is the mock recorder for MockloginAuthenticator.
type MockloginAuthenticatorMockRecorder struct {
	mock *MockloginAuthenticator
}

// NewMockloginAuthenticator creates a new mock instance.
func NewMockloginAuthenticator(ctrl *gomock.Controller) *MockloginAuthenticator {
	mock := &MockloginAuthenticator{ctrl: ctrl}
	mock.recorder = &MockloginAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockloginAuthenticator) EXPECT() *MockloginAuthenticatorMockRecorder {
	return m.recorder
}

// AuthCodeURL mocks base method.
func (m *MockloginAuthenticator) AuthCodeURL(state, nonce string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthCodeURL", state, nonce)
	ret0, _ := ret[0].(string)
	return ret0
}

// AuthCodeURL indicates an expected call of AuthCodeURL.
func (mr *MockloginAuthenticatorMockRecorder) AuthCodeURL(state, nonce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthCodeURL", reflect.TypeOf((*MockloginAuthenticator)(nil).AuthCodeURL), state, nonce)
}

// ExchangeAndVerify mocks base method.
func (m *MockloginAuthenticator) ExchangeAndVerify(ctx context.Context, code, expectedNonce string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeAndVerify", ctx, code, expectedNonce)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeAndVerify indicates an expected call of ExchangeAndVerify.
func (mr *MockloginAuthenticatorMockRecorder) ExchangeAndVerify(ctx, code, expectedNonce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeAndVerify", reflect.TypeOf((*MockloginAuthenticator)(nil).ExchangeAndVerify), ctx, code, expectedNonce)
}
