#!/usr/bin/env bash
#
# Generates an NKey account seed for AUTH_SIGNING_KEY and writes .env.
# Uses the nats-box Docker image so no local tooling is needed.
#
# Run once before `docker compose up`.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
NATS_BOX_IMAGE="natsio/nats-box:latest"

echo "=== mchat — Local Dev Setup ==="
echo ""

if ! command -v docker &>/dev/null; then
  echo "ERROR: docker not found. Install Docker first."
  exit 1
fi

echo "Generating NATS account signing key via nats-box..."

# Generate account NKey seed (starts with SA)
SEED=$(docker run --rm "$NATS_BOX_IMAGE" nk -gen account | grep "^SA")

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh — do not commit this file
# Regenerate with: ./setup.sh

AUTH_SIGNING_KEY=${SEED}
OIDC_ISSUER_URL=http://keycloak:8080/realms/chatapp
OIDC_AUDIENCE=nats-chat
OIDC_VERIFY_AZP=true
EOF

echo ""
echo "Wrote $ENV_FILE"
echo ""
echo "=== Ready! ==="
echo ""
echo "  cd $(dirname "$ENV_FILE")"
echo "  docker compose up -d"
echo ""
echo "  Wait for Keycloak to be ready (~30-60s):"
echo "    docker compose logs -f keycloak"
echo ""
echo "  ──────────────────────────────────────"
echo "  mchat UI:         http://localhost:8091"
echo "  Keycloak Admin:   http://localhost:9090  (admin / admin)"
echo "  NATS Monitoring:  http://localhost:8222"
echo "  ──────────────────────────────────────"
echo ""
echo "  Test users: testuser/testuser  alice/alice"
echo ""
