// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProvisionStore is a mock of ProvisionStore interface.
type MockProvisionStore struct {
	ctrl     *gomock.Controller
	recorder *MockProvisionStoreMockRecorder
	isgomock struct{}
}

// MockProvisionStoreMockRecorder is the mock recorder for MockProvisionStore.
type MockProvisionStoreMockRecorder struct {
	mock *MockProvisionStore
}

// NewMockProvisionStore creates a new mock instance.
func NewMockProvisionStore(ctrl *gomock.Controller) *MockProvisionStore {
	mock := &MockProvisionStore{ctrl: ctrl}
	mock.recorder = &MockProvisionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvisionStore) EXPECT() *MockProvisionStoreMockRecorder {
	return m.recorder
}

// AccountProvisioned mocks base method.
func (m *MockProvisionStore) AccountProvisioned(ctx context.Context, account, siteID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountProvisioned", ctx, account, siteID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountProvisioned indicates an expected call of AccountProvisioned.
func (mr *MockProvisionStoreMockRecorder) AccountProvisioned(ctx, account, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountProvisioned", reflect.TypeOf((*MockProvisionStore)(nil).AccountProvisioned), ctx, account, siteID)
}
