package main

import (
	"fmt"
	"math/rand"
	"sort"
	"time"

	"github.com/hmchangw/chat/pkg/model"
)

// Distribution names the shape of a per-preset random selection.
type Distribution string

const (
	DistUniform Distribution = "uniform"
	DistMixed   Distribution = "mixed"
	DistZipf    Distribution = "zipf"
)

// Range holds an inclusive min/max for integer quantities like content size.
type Range struct {
	Min int
	Max int
}

// historyRequestKind enumerates the history-service request handlers
// exercised by the `history-read` preset.
type historyRequestKind int

const (
	HistoryLoadHistory historyRequestKind = iota
	HistoryGetMessageByID
	HistoryLoadSurrounding
	HistoryGetThreadMessages
)

// searchRequestKind enumerates the search-service request handlers
// exercised by the `search-read` preset.
type searchRequestKind int

const (
	SearchMessagesKind searchRequestKind = iota
	SearchRoomsKind
)

// roomRequestKind enumerates the room-service RPCs exercised by the
// `room-rpc` preset.
type roomRequestKind int

const (
	RoomsListKind roomRequestKind = iota
	RoomsGetKind
	MemberListKind
	RoomCreateKind
	MemberAddKind
)

// builtinSearchTokens is the deterministic 10-token query bag used by the
// `search-read` preset. Drawn from generic English so seeded message
// content (Lorem-style) yields realistic hit rates.
var builtinSearchTokens = []string{
	"hello", "thanks", "team", "review", "deploy",
	"meeting", "update", "today", "release", "status",
}

// Preset is a named, fully deterministic workload specification.
//
// Fixture-shaping fields (Users / Rooms / *Dist / ContentBytes / *Rate)
// drive seeding. Read-scenario fields (HistoryMix) are populated only for
// presets that exercise natsrouter request/reply handlers; they are nil
// for the messaging-pipeline presets.
type Preset struct {
	Name         string
	Users        int
	Rooms        int
	RoomSizeDist Distribution
	SenderDist   Distribution
	ContentBytes Range
	MentionRate  float64
	ThreadRate   float64

	// HistoryMix is the integer-weighted request-type mix for the
	// `history-read` scenario. Keys are exhaustive over historyRequestKind;
	// values are non-negative and conventionally sum to 100.
	HistoryMix map[historyRequestKind]int

	// SearchMix is the integer-weighted request-type mix for the
	// `search-read` scenario, with the same conventions as HistoryMix.
	SearchMix map[searchRequestKind]int

	// SearchTokens is the deterministic bag of query strings the
	// `search-read` scenario draws from when building requests.
	SearchTokens []string

	// SearchScope is the room-scope filter applied to SearchRooms requests.
	// Empty string means "no scope filter" (all room types).
	SearchScope string

	// SearchSize is the requested page size for both SearchMessages and
	// SearchRooms requests. Zero defaults to 20 at the call site (preset
	// is the source of truth, but a zero default avoids breaking older
	// presets that haven't set it).
	SearchSize int

	// RoomMix is the integer-weighted request-type mix for the
	// `room-rpc` scenario. Keys are exhaustive over roomRequestKind;
	// values are non-negative and conventionally sum to 100.
	RoomMix map[roomRequestKind]int

	// WriteIDPrefix is prepended to any IDs / names generated by
	// state-mutating ticks (RoomCreate, MemberAdd) so they're trivially
	// identifiable in forensic checks of the loadgen Mongo database.
	// Zero value = no prefix.
	WriteIDPrefix string
}

var builtinPresets = map[string]Preset{
	"small": {
		Name: "small", Users: 10, Rooms: 5,
		RoomSizeDist: DistUniform, SenderDist: DistUniform,
		ContentBytes: Range{Min: 200, Max: 200},
	},
	"medium": {
		Name: "medium", Users: 1000, Rooms: 100,
		RoomSizeDist: DistUniform, SenderDist: DistUniform,
		ContentBytes: Range{Min: 200, Max: 200},
	},
	"large": {
		Name: "large", Users: 10000, Rooms: 1000,
		RoomSizeDist: DistUniform, SenderDist: DistUniform,
		ContentBytes: Range{Min: 200, Max: 200},
	},
	"realistic": {
		Name: "realistic", Users: 1000, Rooms: 100,
		RoomSizeDist: DistMixed, SenderDist: DistZipf,
		ContentBytes: Range{Min: 50, Max: 2000},
		MentionRate:  0.10,
		ThreadRate:   0.05,
	},
	"history-read": {
		Name: "history-read", Users: 10, Rooms: 5,
		RoomSizeDist: DistUniform, SenderDist: DistUniform,
		ContentBytes: Range{Min: 200, Max: 200},
		HistoryMix: map[historyRequestKind]int{
			HistoryLoadHistory:       60,
			HistoryGetMessageByID:    20,
			HistoryLoadSurrounding:   10,
			HistoryGetThreadMessages: 10,
		},
	},
	"search-read": {
		Name: "search-read", Users: 10, Rooms: 5,
		RoomSizeDist: DistUniform, SenderDist: DistUniform,
		ContentBytes: Range{Min: 200, Max: 200},
		SearchMix: map[searchRequestKind]int{
			SearchMessagesKind: 50,
			SearchRoomsKind:    50,
		},
		SearchTokens: builtinSearchTokens,
		SearchScope:  "channel",
		SearchSize:   20,
	},
	"room-rpc": {
		Name: "room-rpc", Users: 1000, Rooms: 100,
		RoomSizeDist: DistUniform, SenderDist: DistUniform,
		ContentBytes: Range{Min: 200, Max: 200},
		MentionRate:  0.10,
		RoomMix: map[roomRequestKind]int{
			RoomsListKind:  60,
			RoomsGetKind:   20,
			MemberListKind: 10,
			RoomCreateKind: 8,
			MemberAddKind:  2,
		},
		WriteIDPrefix: "loadgen-",
	},
}

// BuiltinPreset looks up a preset by name.
func BuiltinPreset(name string) (Preset, bool) {
	p, ok := builtinPresets[name]
	return p, ok
}

// pickWeighted draws a key from the weights map with probability proportional
// to its weight. Iteration order is sorted by key to keep selection
// deterministic for a given (rand.Rand, weights) pair across runs. Total
// weight must be > 0; the caller owns that invariant since both callers
// derive weights from the preset registry where the invariant is enforced.
func pickWeighted[K ~int](r *rand.Rand, weights map[K]int) K {
	keys := make([]K, 0, len(weights))
	for k := range weights {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })

	total := 0
	for _, k := range keys {
		total += weights[k]
	}
	pick := r.Intn(total)
	cum := 0
	for _, k := range keys {
		cum += weights[k]
		if pick < cum {
			return k
		}
	}
	return keys[len(keys)-1] // unreachable when total>0
}

func pickHistoryKind(r *rand.Rand, weights map[historyRequestKind]int) historyRequestKind {
	return pickWeighted(r, weights)
}

func pickSearchKind(r *rand.Rand, weights map[searchRequestKind]int) searchRequestKind {
	return pickWeighted(r, weights)
}

func pickRoomKind(r *rand.Rand, weights map[roomRequestKind]int) roomRequestKind {
	return pickWeighted(r, weights)
}

// Fixtures is the full seed data for a preset run.
type Fixtures struct {
	Users         []model.User
	Rooms         []model.Room
	Subscriptions []model.Subscription
}

var (
	engNameBank     = []string{"Alice Wang", "Bob Chen", "Carol Lee", "Dave Liu", "Eve Zhang"}
	chineseNameBank = []string{"愛麗絲", "鮑勃", "卡蘿", "戴夫", "伊芙"}
)

// BuildFixtures is a pure function of (preset, seed, siteID) producing the
// full fixture set. Two calls with equal inputs produce equal outputs.
func BuildFixtures(p *Preset, seed int64, siteID string) Fixtures {
	r := rand.New(rand.NewSource(seed))
	now := time.Unix(0, 0).UTC() // fixed so output is deterministic

	users := make([]model.User, p.Users)
	for i := 0; i < p.Users; i++ {
		users[i] = model.User{
			ID:          fmt.Sprintf("u-%06d", i),
			Account:     fmt.Sprintf("user-%d", i),
			SiteID:      siteID,
			EngName:     engNameBank[i%len(engNameBank)],
			ChineseName: chineseNameBank[i%len(chineseNameBank)],
		}
	}

	rooms := make([]model.Room, p.Rooms)
	// realistic: last 10% of rooms are DMs
	dmStart := p.Rooms
	if p.RoomSizeDist == DistMixed {
		dmStart = p.Rooms - p.Rooms/10
	}
	for i := 0; i < p.Rooms; i++ {
		rtype := model.RoomTypeChannel
		if i >= dmStart {
			rtype = model.RoomTypeDM
		}
		rooms[i] = model.Room{
			ID:        fmt.Sprintf("room-%06d", i),
			Name:      fmt.Sprintf("room-%d", i),
			Type:      rtype,
			SiteID:    siteID,
			UserCount: 0, // filled after membership
			CreatedAt: now,
			UpdatedAt: now,
		}
	}

	var subs []model.Subscription
	for i := range rooms {
		members := pickMembers(r, p, i, p.Rooms, &rooms[i], users)
		rooms[i].UserCount = len(members)
		for j := range members {
			subs = append(subs, model.Subscription{
				ID:       fmt.Sprintf("sub-%s-%s", rooms[i].ID, members[j].ID),
				User:     model.SubscriptionUser{ID: members[j].ID, Account: members[j].Account},
				RoomID:   rooms[i].ID,
				SiteID:   siteID,
				Roles:    []model.Role{model.RoleMember},
				JoinedAt: now,
			})
		}
	}
	return Fixtures{Users: users, Rooms: rooms, Subscriptions: subs}
}

func pickMembers(r *rand.Rand, p *Preset, roomIdx, totalRooms int, room *model.Room, users []model.User) []model.User {
	if room.Type == model.RoomTypeDM {
		// Two distinct users.
		i := r.Intn(len(users))
		j := r.Intn(len(users) - 1)
		if j >= i {
			j++
		}
		return []model.User{users[i], users[j]}
	}
	switch p.RoomSizeDist {
	case DistMixed:
		// 10% of rooms get up to 500 members; rest get 2-20.
		size := 2 + r.Intn(19)
		if r.Intn(10) == 0 {
			size = 2 + r.Intn(499)
		}
		return sampleWithoutReplacement(r, users, size)
	default:
		// Assign each user to exactly one room via round-robin so that every
		// user appears in at least one room.
		var members []model.User
		for i := range users {
			if i%totalRooms == roomIdx {
				members = append(members, users[i])
			}
		}
		if len(members) < 2 {
			// Pad with random extras to ensure at least 2 members.
			extra := sampleWithoutReplacement(r, users, 2)
			seen := make(map[string]bool)
			for i := range members {
				seen[members[i].ID] = true
			}
			for i := range extra {
				if !seen[extra[i].ID] {
					members = append(members, extra[i])
					seen[extra[i].ID] = true
				}
				if len(members) >= 2 {
					break
				}
			}
		}
		return members
	}
}

func sampleWithoutReplacement(r *rand.Rand, users []model.User, n int) []model.User {
	if n > len(users) {
		n = len(users)
	}
	idx := r.Perm(len(users))[:n]
	out := make([]model.User, n)
	for i, k := range idx {
		out[i] = users[k]
	}
	return out
}
