// Code generated by MockGen. DO NOT EDIT.
// Source: peer_client.go
//
// Generated by this command:
//
//	mockgen -source=peer_client.go -destination=mock_peer_client_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockPeerPresenceClient is a mock of PeerPresenceClient interface.
type MockPeerPresenceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPeerPresenceClientMockRecorder
	isgomock struct{}
}

// MockPeerPresenceClientMockRecorder is the mock recorder for MockPeerPresenceClient.
type MockPeerPresenceClientMockRecorder struct {
	mock *MockPeerPresenceClient
}

// NewMockPeerPresenceClient creates a new mock instance.
func NewMockPeerPresenceClient(ctrl *gomock.Controller) *MockPeerPresenceClient {
	mock := &MockPeerPresenceClient{ctrl: ctrl}
	mock.recorder = &MockPeerPresenceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeerPresenceClient) EXPECT() *MockPeerPresenceClientMockRecorder {
	return m.recorder
}

// QueryPeer mocks base method.
func (m *MockPeerPresenceClient) QueryPeer(ctx context.Context, siteID string, accounts []string) ([]model.PresenceState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryPeer", ctx, siteID, accounts)
	ret0, _ := ret[0].([]model.PresenceState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryPeer indicates an expected call of QueryPeer.
func (mr *MockPeerPresenceClientMockRecorder) QueryPeer(ctx, siteID, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryPeer", reflect.TypeOf((*MockPeerPresenceClient)(nil).QueryPeer), ctx, siteID, accounts)
}
