// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockavatarStore is a mock of avatarStore interface.
type MockavatarStore struct {
	ctrl     *gomock.Controller
	recorder *MockavatarStoreMockRecorder
	isgomock struct{}
}

// MockavatarStoreMockRecorder is the mock recorder for MockavatarStore.
type MockavatarStoreMockRecorder struct {
	mock *MockavatarStore
}

// NewMockavatarStore creates a new mock instance.
func NewMockavatarStore(ctrl *gomock.Controller) *MockavatarStore {
	mock := &MockavatarStore{ctrl: ctrl}
	mock.recorder = &MockavatarStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockavatarStore) EXPECT() *MockavatarStoreMockRecorder {
	return m.recorder
}

// Avatar mocks base method.
func (m *MockavatarStore) Avatar(ctx context.Context, subjectType model.AvatarSubjectType, subjectID string) (*model.Avatar, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Avatar", ctx, subjectType, subjectID)
	ret0, _ := ret[0].(*model.Avatar)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Avatar indicates an expected call of Avatar.
func (mr *MockavatarStoreMockRecorder) Avatar(ctx, subjectType, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Avatar", reflect.TypeOf((*MockavatarStore)(nil).Avatar), ctx, subjectType, subjectID)
}

// BotSite mocks base method.
func (m *MockavatarStore) BotSite(ctx context.Context, account string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotSite", ctx, account)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BotSite indicates an expected call of BotSite.
func (mr *MockavatarStoreMockRecorder) BotSite(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotSite", reflect.TypeOf((*MockavatarStore)(nil).BotSite), ctx, account)
}

// EmployeeID mocks base method.
func (m *MockavatarStore) EmployeeID(ctx context.Context, account string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmployeeID", ctx, account)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EmployeeID indicates an expected call of EmployeeID.
func (mr *MockavatarStoreMockRecorder) EmployeeID(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmployeeID", reflect.TypeOf((*MockavatarStore)(nil).EmployeeID), ctx, account)
}

// RoomSite mocks base method.
func (m *MockavatarStore) RoomSite(ctx context.Context, roomID string) (string, model.RoomType, string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomSite", ctx, roomID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(model.RoomType)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(bool)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// RoomSite indicates an expected call of RoomSite.
func (mr *MockavatarStoreMockRecorder) RoomSite(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomSite", reflect.TypeOf((*MockavatarStore)(nil).RoomSite), ctx, roomID)
}

// SetBotAvatar mocks base method.
func (m *MockavatarStore) SetBotAvatar(ctx context.Context, av *model.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBotAvatar", ctx, av)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBotAvatar indicates an expected call of SetBotAvatar.
func (mr *MockavatarStoreMockRecorder) SetBotAvatar(ctx, av any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBotAvatar", reflect.TypeOf((*MockavatarStore)(nil).SetBotAvatar), ctx, av)
}
