// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/pkg/msgkeystore (interfaces: KeyStore)
//
// Generated by this command:
//
//	mockgen -destination=mock_keystore_test.go -package=msgcrypto github.com/hmchangw/chat/pkg/msgkeystore KeyStore
//

// Package msgcrypto is a generated GoMock package.
package msgcrypto

import (
	context "context"
	reflect "reflect"

	msgkeystore "github.com/hmchangw/chat/pkg/msgkeystore"
	gomock "go.uber.org/mock/gomock"
)

// MockKeyStore is a mock of KeyStore interface.
type MockKeyStore struct {
	ctrl     *gomock.Controller
	recorder *MockKeyStoreMockRecorder
	isgomock struct{}
}

// MockKeyStoreMockRecorder is the mock recorder for MockKeyStore.
type MockKeyStoreMockRecorder struct {
	mock *MockKeyStore
}

// NewMockKeyStore creates a new mock instance.
func NewMockKeyStore(ctrl *gomock.Controller) *MockKeyStore {
	mock := &MockKeyStore{ctrl: ctrl}
	mock.recorder = &MockKeyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyStore) EXPECT() *MockKeyStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockKeyStore) Delete(ctx context.Context, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockKeyStoreMockRecorder) Delete(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockKeyStore)(nil).Delete), ctx, roomID)
}

// Get mocks base method.
func (m *MockKeyStore) Get(ctx context.Context, roomID string) (*msgkeystore.VersionedKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, roomID)
	ret0, _ := ret[0].(*msgkeystore.VersionedKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockKeyStoreMockRecorder) Get(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKeyStore)(nil).Get), ctx, roomID)
}

// GetByVersion mocks base method.
func (m *MockKeyStore) GetByVersion(ctx context.Context, roomID string, version int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByVersion", ctx, roomID, version)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByVersion indicates an expected call of GetByVersion.
func (mr *MockKeyStoreMockRecorder) GetByVersion(ctx, roomID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByVersion", reflect.TypeOf((*MockKeyStore)(nil).GetByVersion), ctx, roomID, version)
}

// Rotate mocks base method.
func (m *MockKeyStore) Rotate(ctx context.Context, roomID string, newKey []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx, roomID, newKey)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rotate indicates an expected call of Rotate.
func (mr *MockKeyStoreMockRecorder) Rotate(ctx, roomID, newKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockKeyStore)(nil).Rotate), ctx, roomID, newKey)
}

// Set mocks base method.
func (m *MockKeyStore) Set(ctx context.Context, roomID string, key []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, roomID, key)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockKeyStoreMockRecorder) Set(ctx, roomID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockKeyStore)(nil).Set), ctx, roomID, key)
}
