package readers

import (
	"context"
	"fmt"
	"strings"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// MongoRoomsReader watches the rooms collection for newly-inserted rows
// (createdAt >= start). Polls every 100ms.
//
// Filter rationale: createdAt-based, NOT _id-prefix-based. Room IDs are
// server-generated by pkg/idgen.GenerateID() (17-char base62, no
// scenario-controllable prefix) at room-service/handler.go:333, then
// written verbatim by room-worker. So an _id-prefix filter would
// exclude every scenario-created room. Pre-existing seeded rooms are
// excluded by timestamp instead (seed JSON sets createdAt:
// 2025-01-01T00:00:00Z, older than any scenario's start).
type MongoRoomsReader struct {
	Client *mongo.Client
	DBName string
}

// NewMongoRoomsReader returns a MongoRoomsReader backed by the given client and database.
func NewMongoRoomsReader(c *mongo.Client, dbName string) *MongoRoomsReader {
	return &MongoRoomsReader{Client: c, DBName: dbName}
}

// Watch starts a polling goroutine that emits Events for each room
// created at or after `start`. Mongo documents cannot natively carry
// W3C trace context, so the reader leaves Event.Traceparent empty —
// the Observer's scope-aware merge loop stamps the scenario's trace
// IFF room-worker is in this scenario's sequence (per the Reader
// interface contract).
func (r *MongoRoomsReader) Watch(ctx context.Context, _ string, start time.Time) (<-chan Event, error) {
	ch := make(chan Event, 16)
	go func() {
		defer close(ch)
		seen := map[string]struct{}{}
		t := time.NewTicker(100 * time.Millisecond)
		defer t.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case <-t.C:
				docs, err := r.fetchSince(ctx, start)
				if err != nil {
					continue
				}
				for _, d := range docs {
					id, _ := d["_id"].(string)
					if id == "" {
						continue
					}
					if _, ok := seen[id]; ok {
						continue
					}
					seen[id] = struct{}{}
					// Use observation time (not doc.createdAt). createdAt is
					// stamped by room-service when it publishes the canonical
					// event — BEFORE it replies — so it would actually be
					// earlier than the reply event and would zero out the
					// room-worker step's duration attribution. Observation
					// time is +0..100ms (poll cadence) but reflects the real
					// pipeline latency we want to attribute to room-worker.
					ch <- Event{
						Location:  "mongo.rooms",
						Timestamp: time.Now(),
						OwnerSvc:  "room-worker",
						Payload:   d,
					}
				}
			}
		}
	}()
	return ch, nil
}

func (r *MongoRoomsReader) fetchSince(ctx context.Context, start time.Time) ([]map[string]any, error) {
	coll := r.Client.Database(r.DBName).Collection("rooms")
	filter := bson.M{"createdAt": bson.M{"$gte": start}}
	cur, err := coll.Find(ctx, filter)
	if err != nil {
		return nil, fmt.Errorf("mongo.rooms find: %w", err)
	}
	defer cur.Close(ctx) //nolint:errcheck
	var out []map[string]any
	for cur.Next(ctx) {
		var doc map[string]any
		if err := cur.Decode(&doc); err != nil {
			return nil, fmt.Errorf("mongo.rooms decode: %w", err)
		}
		out = append(out, doc)
	}
	if err := cur.Err(); err != nil && !strings.Contains(err.Error(), "context") {
		return nil, fmt.Errorf("mongo.rooms cursor: %w", err)
	}
	return out, nil
}
