#!/usr/bin/env bash
#
# Generates per-site NATS operator + account keys and writes nats.conf,
# backend.creds, account.seed, and <site>.env for the two local-dev NATS
# instances (site-a, site-b). Uses the nats-box Docker image so it works on
# any OS without requiring local nsc/nk installation.
#
# Also writes legacy single-site artifacts (docker-local/{nats.conf,
# backend.creds,.env}) as copies of site-a's, so service composes that still
# reference them keep working during the multi-site transition. Stage 4 of
# the multisite rollout removes these legacy files.
#
# Run once before `make deps-up`.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FRONTEND_ENV_FILE="$REPO_ROOT/chat-frontend/.env.local"
NATS_BOX_IMAGE="natsio/nats-box:latest"

# Per-site host port assignments. Site-a keeps the historical defaults so
# standalone `docker compose -f <service>/deploy/docker-compose.yml up` still
# matches today's behavior; site-b shifts by 1 on each exposed service.
SITE_A_AUTH_PORT=8080
SITE_B_AUTH_PORT=8081
SITE_A_HISTORY_PORT=8082
SITE_B_HISTORY_PORT=8083
SITE_A_ROOM_PORT=8084
SITE_B_ROOM_PORT=8085
SITE_A_SEARCH_PORT=8086
SITE_B_SEARCH_PORT=8087
SITE_A_MOCK_USER_PORT=8088
SITE_B_MOCK_USER_PORT=8089
SITE_A_SEARCH_METRICS_PORT=9090
SITE_B_SEARCH_METRICS_PORT=9091

echo "=== docker-local — Multi-site NATS setup (site-a + site-b) ==="
echo ""

if ! command -v docker &>/dev/null; then
  echo "ERROR: docker not found. Install Docker first."
  exit 1
fi

# generate_site SITE NATS_HOST AUTH_PORT HISTORY_PORT ROOM_PORT SEARCH_PORT MOCK_USER_PORT SEARCH_METRICS_PORT
generate_site() {
  local site="$1"
  local nats_host="$2"
  local auth_port="$3"
  local history_port="$4"
  local room_port="$5"
  local search_port="$6"
  local mock_user_port="$7"
  local search_metrics_port="$8"

  local site_dir="$SCRIPT_DIR/$site"
  local env_file="$SCRIPT_DIR/${site}.env"
  mkdir -p "$site_dir"

  echo "--- Generating $site keys ---"
  local tmpdir
  tmpdir=$(mktemp -d)

  docker run --rm \
    -v "$tmpdir:/output" \
    -e SITE="$site" \
    "$NATS_BOX_IMAGE" \
    sh -c '
      set -e

      nsc add operator --name "localdev-${SITE}" --sys 2>&1 | sed "s/^/  /"
      nsc env -o "localdev-${SITE}" >/dev/null 2>&1

      nsc add account --name chatapp 2>&1 | sed "s/^/  /"
      nsc edit account chatapp --js-mem-storage 512M --js-disk-storage 5G --js-streams 10 2>&1 | sed "s/^/  /"

      nsc describe operator --raw > /output/operator.jwt
      nsc describe account chatapp --raw > /output/account.jwt
      nsc describe account SYS --raw > /output/sys.jwt

      nsc describe account chatapp 2>/dev/null | grep "Account ID" | awk -F"|" "{gsub(/[ \t]/, \"\", \$3); print \$3}" > /output/account_pub.txt
      nsc describe account SYS 2>/dev/null | grep "Account ID" | awk -F"|" "{gsub(/[ \t]/, \"\", \$3); print \$3}" > /output/sys_pub.txt

      ACCOUNT_PUB=$(cat /output/account_pub.txt)
      SEED_FILE=$(find /root/.local/share/nats/nsc/keys -name "${ACCOUNT_PUB}.nk" 2>/dev/null | head -1)
      if [ -z "$SEED_FILE" ]; then
        SEED_FILE=$(find /nsc -name "${ACCOUNT_PUB}.nk" 2>/dev/null | head -1)
      fi
      if [ -z "$SEED_FILE" ]; then
        echo "ERROR: Could not find account seed for ${ACCOUNT_PUB}"
        exit 1
      fi
      cat "$SEED_FILE" > /output/account_seed.txt

      nsc add user --account chatapp --name backend
      nsc edit user --account chatapp --name backend --allow-sub ">" --allow-pub ">"
      nsc generate creds --account chatapp --name backend > /output/backend.creds
    '

  cp "$tmpdir/backend.creds" "$site_dir/backend.creds"
  cp "$tmpdir/account_seed.txt" "$site_dir/account.seed"
  # 0644 on backend.creds: service containers run as non-root (uid 10001)
  # and bind-mount it read-only — the in-container user must read it.
  # Acceptable only because this is a throwaway local-dev credential.
  chmod 644 "$site_dir/backend.creds"
  chmod 600 "$site_dir/account.seed"

  local op_jwt acc_jwt sys_jwt acc_pub sys_pub acc_seed
  op_jwt=$(cat "$tmpdir/operator.jwt")
  acc_jwt=$(cat "$tmpdir/account.jwt")
  sys_jwt=$(cat "$tmpdir/sys.jwt")
  acc_pub=$(cat "$tmpdir/account_pub.txt")
  sys_pub=$(cat "$tmpdir/sys_pub.txt")
  acc_seed=$(cat "$tmpdir/account_seed.txt")

  cat > "$site_dir/nats.conf" <<EOF
# Generated by docker-local/setup.sh — do not commit this file.
# Regenerate with: ./docker-local/setup.sh

port: 4222
http_port: 8222

operator: ${op_jwt}

resolver: MEMORY

resolver_preload {
  ${acc_pub}: ${acc_jwt}
  ${sys_pub}: ${sys_jwt}
}

jetstream {
  store_dir: /data/jetstream
  max_mem: 1G
  max_file: 10G
}

websocket {
  port: 9222
  no_tls: true
}
EOF

  cat > "$env_file" <<EOF
# Generated by docker-local/setup.sh — do not commit this file.
# Regenerate with: ./docker-local/setup.sh

SITE_ID=${site}
NATS_HOST=${nats_host}

# auth-service signs user JWTs with the chatapp account nkey (private seed).
# All other microservices authenticate with backend.creds via NATS_CREDS_FILE.
AUTH_SIGNING_KEY=${acc_seed}

# Bypass OIDC in auth-service; flip to false to test the OIDC flow.
DEV_MODE=true

# Host port mappings for services that publish a port on the host.
AUTH_HOST_PORT=${auth_port}
HISTORY_HOST_PORT=${history_port}
ROOM_HOST_PORT=${room_port}
SEARCH_HOST_PORT=${search_port}
MOCK_USER_HOST_PORT=${mock_user_port}
SEARCH_METRICS_HOST_PORT=${search_metrics_port}
EOF
  chmod 600 "$env_file"

  echo "  Account Public Key: $acc_pub"
  echo "  Wrote $site_dir/nats.conf"
  echo "  Wrote $site_dir/backend.creds"
  echo "  Wrote $site_dir/account.seed"
  echo "  Wrote $env_file"
  echo ""

  rm -rf "$tmpdir"
}

generate_site site-a nats-a \
  "$SITE_A_AUTH_PORT" "$SITE_A_HISTORY_PORT" "$SITE_A_ROOM_PORT" \
  "$SITE_A_SEARCH_PORT" "$SITE_A_MOCK_USER_PORT" "$SITE_A_SEARCH_METRICS_PORT"

generate_site site-b nats-b \
  "$SITE_B_AUTH_PORT" "$SITE_B_HISTORY_PORT" "$SITE_B_ROOM_PORT" \
  "$SITE_B_SEARCH_PORT" "$SITE_B_MOCK_USER_PORT" "$SITE_B_SEARCH_METRICS_PORT"

# Clean up legacy single-site artifacts (no service compose references them
# anymore after stage 2). Safe to delete unconditionally.
rm -f "$SCRIPT_DIR/.env" "$SCRIPT_DIR/nats.conf" "$SCRIPT_DIR/backend.creds"

# chat-frontend/.env.local feeds `npm run dev` (Vite). Written only on first
# run so devs can edit it (e.g. point at staging) without losing changes.
if [ ! -f "$FRONTEND_ENV_FILE" ]; then
  cat > "$FRONTEND_ENV_FILE" <<EOF
VITE_AUTH_URL=http://localhost:${SITE_A_AUTH_PORT}
VITE_NATS_URL=ws://localhost:9222
VITE_DEFAULT_SITE_ID=site-a
EOF
fi

echo "=== Ready! ==="
echo ""
echo "  # Start third-party deps (both NATSes + shared Mongo/Cassandra/ES/etc.)"
echo "  make deps-up"
echo ""
echo "  # Start every microservice for both sites (foreground, streams logs)"
echo "  make up"
echo ""
echo "  ──────────────────────────────────────"
echo "  site-a NATS:        nats://localhost:4222   (ws: 9222, monitor: 8222)"
echo "  site-b NATS:        nats://localhost:4322   (ws: 9322, monitor: 8322)"
echo "  ──────────────────────────────────────"
echo ""
