// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/history-service/internal/service (interfaces: MessageRepository,SubscriptionRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repository.go -package=mocks . MessageRepository,SubscriptionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	cassrepo "github.com/hmchangw/chat/history-service/internal/cassrepo"
	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// GetLatestMessages mocks base method.
func (m *MockMessageRepository) GetLatestMessages(ctx context.Context, roomID string, q cassrepo.PageRequest) (cassrepo.Page[model.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestMessages", ctx, roomID, q)
	ret0, _ := ret[0].(cassrepo.Page[model.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestMessages indicates an expected call of GetLatestMessages.
func (mr *MockMessageRepositoryMockRecorder) GetLatestMessages(ctx, roomID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestMessages", reflect.TypeOf((*MockMessageRepository)(nil).GetLatestMessages), ctx, roomID, q)
}

// GetMessageByID mocks base method.
func (m *MockMessageRepository) GetMessageByID(ctx context.Context, roomID, messageID string) (*model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByID", ctx, roomID, messageID)
	ret0, _ := ret[0].(*model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByID indicates an expected call of GetMessageByID.
func (mr *MockMessageRepositoryMockRecorder) GetMessageByID(ctx, roomID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByID", reflect.TypeOf((*MockMessageRepository)(nil).GetMessageByID), ctx, roomID, messageID)
}

// GetMessagesAfter mocks base method.
func (m *MockMessageRepository) GetMessagesAfter(ctx context.Context, roomID string, after time.Time, q cassrepo.PageRequest) (cassrepo.Page[model.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesAfter", ctx, roomID, after, q)
	ret0, _ := ret[0].(cassrepo.Page[model.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesAfter indicates an expected call of GetMessagesAfter.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesAfter(ctx, roomID, after, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesAfter", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesAfter), ctx, roomID, after, q)
}

// GetMessagesBefore mocks base method.
func (m *MockMessageRepository) GetMessagesBefore(ctx context.Context, roomID string, before time.Time, q cassrepo.PageRequest) (cassrepo.Page[model.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBefore", ctx, roomID, before, q)
	ret0, _ := ret[0].(cassrepo.Page[model.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBefore indicates an expected call of GetMessagesBefore.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesBefore(ctx, roomID, before, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBefore", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesBefore), ctx, roomID, before, q)
}

// GetMessagesBetweenAsc mocks base method.
func (m *MockMessageRepository) GetMessagesBetweenAsc(ctx context.Context, roomID string, after, before time.Time, inclusive bool, q cassrepo.PageRequest) (cassrepo.Page[model.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBetweenAsc", ctx, roomID, after, before, inclusive, q)
	ret0, _ := ret[0].(cassrepo.Page[model.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBetweenAsc indicates an expected call of GetMessagesBetweenAsc.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesBetweenAsc(ctx, roomID, after, before, inclusive, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBetweenAsc", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesBetweenAsc), ctx, roomID, after, before, inclusive, q)
}

// GetMessagesBetweenDesc mocks base method.
func (m *MockMessageRepository) GetMessagesBetweenDesc(ctx context.Context, roomID string, since, before time.Time, q cassrepo.PageRequest) (cassrepo.Page[model.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBetweenDesc", ctx, roomID, since, before, q)
	ret0, _ := ret[0].(cassrepo.Page[model.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBetweenDesc indicates an expected call of GetMessagesBetweenDesc.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesBetweenDesc(ctx, roomID, since, before, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBetweenDesc", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesBetweenDesc), ctx, roomID, since, before, q)
}

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// GetHistorySharedSince mocks base method.
func (m *MockSubscriptionRepository) GetHistorySharedSince(ctx context.Context, username, roomID string) (*time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistorySharedSince", ctx, username, roomID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetHistorySharedSince indicates an expected call of GetHistorySharedSince.
func (mr *MockSubscriptionRepositoryMockRecorder) GetHistorySharedSince(ctx, username, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistorySharedSince", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetHistorySharedSince), ctx, username, roomID)
}
