// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/history-service/internal/service (interfaces: MessageRepository,SubscriptionRepository,ContentDecryptor)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repository.go -package=mocks . MessageRepository,SubscriptionRepository,ContentDecryptor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	cassrepo "github.com/hmchangw/chat/history-service/internal/cassrepo"
	models "github.com/hmchangw/chat/history-service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// GetAllMessagesAsc mocks base method.
func (m *MockMessageRepository) GetAllMessagesAsc(ctx context.Context, roomID string, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMessagesAsc", ctx, roomID, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMessagesAsc indicates an expected call of GetAllMessagesAsc.
func (mr *MockMessageRepositoryMockRecorder) GetAllMessagesAsc(ctx, roomID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMessagesAsc", reflect.TypeOf((*MockMessageRepository)(nil).GetAllMessagesAsc), ctx, roomID, q)
}

// GetMessage mocks base method.
func (m *MockMessageRepository) GetMessage(ctx context.Context, roomID string, createdAt time.Time, messageID string) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, roomID, createdAt, messageID)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockMessageRepositoryMockRecorder) GetMessage(ctx, roomID, createdAt, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockMessageRepository)(nil).GetMessage), ctx, roomID, createdAt, messageID)
}

// GetMessagesAfter mocks base method.
func (m *MockMessageRepository) GetMessagesAfter(ctx context.Context, roomID string, after time.Time, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesAfter", ctx, roomID, after, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesAfter indicates an expected call of GetMessagesAfter.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesAfter(ctx, roomID, after, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesAfter", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesAfter), ctx, roomID, after, q)
}

// GetMessagesBefore mocks base method.
func (m *MockMessageRepository) GetMessagesBefore(ctx context.Context, roomID string, before time.Time, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBefore", ctx, roomID, before, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBefore indicates an expected call of GetMessagesBefore.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesBefore(ctx, roomID, before, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBefore", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesBefore), ctx, roomID, before, q)
}

// GetMessagesBetweenDesc mocks base method.
func (m *MockMessageRepository) GetMessagesBetweenDesc(ctx context.Context, roomID string, since, before time.Time, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBetweenDesc", ctx, roomID, since, before, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBetweenDesc indicates an expected call of GetMessagesBetweenDesc.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesBetweenDesc(ctx, roomID, since, before, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBetweenDesc", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesBetweenDesc), ctx, roomID, since, before, q)
}

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// GetHistorySharedSince mocks base method.
func (m *MockSubscriptionRepository) GetHistorySharedSince(ctx context.Context, account, roomID string) (*time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistorySharedSince", ctx, account, roomID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetHistorySharedSince indicates an expected call of GetHistorySharedSince.
func (mr *MockSubscriptionRepositoryMockRecorder) GetHistorySharedSince(ctx, account, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistorySharedSince", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetHistorySharedSince), ctx, account, roomID)
}

// MockContentDecryptor is a mock of ContentDecryptor interface.
type MockContentDecryptor struct {
	ctrl     *gomock.Controller
	recorder *MockContentDecryptorMockRecorder
	isgomock struct{}
}

// MockContentDecryptorMockRecorder is the mock recorder for MockContentDecryptor.
type MockContentDecryptorMockRecorder struct {
	mock *MockContentDecryptor
}

// NewMockContentDecryptor creates a new mock instance.
func NewMockContentDecryptor(ctrl *gomock.Controller) *MockContentDecryptor {
	mock := &MockContentDecryptor{ctrl: ctrl}
	mock.recorder = &MockContentDecryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentDecryptor) EXPECT() *MockContentDecryptorMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockContentDecryptor) Decrypt(ctx context.Context, roomID, ciphertext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ctx, roomID, ciphertext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockContentDecryptorMockRecorder) Decrypt(ctx, roomID, ciphertext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockContentDecryptor)(nil).Decrypt), ctx, roomID, ciphertext)
}
