// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/history-service/internal/service (interfaces: MessageRepository,SubscriptionRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repository.go -package=mocks . MessageRepository,SubscriptionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// GetMessageByID mocks base method.
func (m *MockMessageRepository) GetMessageByID(ctx context.Context, roomID, messageID string) (*model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByID", ctx, roomID, messageID)
	ret0, _ := ret[0].(*model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByID indicates an expected call of GetMessageByID.
func (mr *MockMessageRepositoryMockRecorder) GetMessageByID(ctx, roomID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByID", reflect.TypeOf((*MockMessageRepository)(nil).GetMessageByID), ctx, roomID, messageID)
}

// GetMessagesAfter mocks base method.
func (m *MockMessageRepository) GetMessagesAfter(ctx context.Context, roomID string, after time.Time, limit int) ([]model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesAfter", ctx, roomID, after, limit)
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesAfter indicates an expected call of GetMessagesAfter.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesAfter(ctx, roomID, after, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesAfter", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesAfter), ctx, roomID, after, limit)
}

// GetMessagesBefore mocks base method.
func (m *MockMessageRepository) GetMessagesBefore(ctx context.Context, roomID string, since, before time.Time, limit int) ([]model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBefore", ctx, roomID, since, before, limit)
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBefore indicates an expected call of GetMessagesBefore.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesBefore(ctx, roomID, since, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBefore", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesBefore), ctx, roomID, since, before, limit)
}

// GetSurroundingMessages mocks base method.
func (m *MockMessageRepository) GetSurroundingMessages(ctx context.Context, roomID, messageID string, limit int) ([]model.Message, []model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSurroundingMessages", ctx, roomID, messageID, limit)
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].([]model.Message)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSurroundingMessages indicates an expected call of GetSurroundingMessages.
func (mr *MockMessageRepositoryMockRecorder) GetSurroundingMessages(ctx, roomID, messageID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSurroundingMessages", reflect.TypeOf((*MockMessageRepository)(nil).GetSurroundingMessages), ctx, roomID, messageID, limit)
}

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// GetHistorySharedSince mocks base method.
func (m *MockSubscriptionRepository) GetHistorySharedSince(ctx context.Context, userID, roomID string) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistorySharedSince", ctx, userID, roomID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistorySharedSince indicates an expected call of GetHistorySharedSince.
func (mr *MockSubscriptionRepositoryMockRecorder) GetHistorySharedSince(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistorySharedSince", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetHistorySharedSince), ctx, userID, roomID)
}

// GetSubscription mocks base method.
func (m *MockSubscriptionRepository) GetSubscription(ctx context.Context, userID, roomID string) (*model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", ctx, userID, roomID)
	ret0, _ := ret[0].(*model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockSubscriptionRepositoryMockRecorder) GetSubscription(ctx, userID, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetSubscription), ctx, userID, roomID)
}
